name: FaceFinder
targets:
  FaceFinder:
    type: application
    platform: iOS
    deploymentTarget: "16.0"
    sources:
      - SocialFinder
    info:
      path: SocialFinder/Info.plist
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.facefinder.app
        TARGETED_DEVICE_FAMILY: 1
        INFOPLIST_FILE: SocialFinder/Info.plist
        SWIFT_VERSION: 5.0
        MARKETING_VERSION: 2.0
        CURRENT_PROJECT_VERSION: 2
